%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
# image_topic: "/left_camera/image"

CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1439.1, 0.0, 1219.1,
         0.0, 1438.8, 1023.3,
         0.0, 0.0, 1.0]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.0277, 0.0430, 0, 0, 0]

Camera.width: 2448
Camera.height: 2048

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.00166863,-0.999761,-0.0217777,0.050816,
          0.00340938,0.0217833,-0.999757,-0.0625162,
          0.999993,0.00159398,0.00344491,-0.127486,
          0,0,0,1]