%YAML:1.0

LiDARNumber: 4
ImageNumber: 4
DataPath: "/media/sam/LiT7/data/fba/new_device/calib/ex_1/"
CameraFoV: 70

# Params for Canny Edge Extraction
Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 1
Voxel.eigen_ratio: 0.05
Voxel.down_sample_size: 0.02
Plane.min_points_size: 60
Plane.normal_theta_min: 10
Plane.normal_theta_max: 170
Plane.max_size: 5
Ransac.dis_threshold: 0.025
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.08
Edge.max_dis_threshold: 0.15

# Params for color point clouds
Color.dense: 10
Color.intensity_threshold: 10