%YAML:1.0

LiDARNumber: 1
ImageNumber: 1
DataPath: "/media/sam/CR7/20230613_shenzhen_rosbag/bl/"

# Initial extrinsic (usually provided by hand measurement or cad design)
# ExtrinsicMat: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [0.0,   -1.0,   0.0,    0.0,
#          0.0,  0.0,  -1.0,    0.0,
#          1.0,   0.0,    0.0,    0.0,
#          0.0,   0.0,    0.0,    1.0]

# Params for Canny Edge Extraction
Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 1
Voxel.eigen_ratio: 0.05
Voxel.down_sample_size: 0.02
Plane.min_points_size: 60
Plane.normal_theta_min: 30
Plane.normal_theta_max: 150
Plane.max_size: 5
Ransac.dis_threshold: 0.025
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.08
Edge.max_dis_threshold: 0.15

# Params for color point clouds
Color.dense: 10
Color.intensity_threshold: 10
